In [1]:
print("Hello")

Hello


## Creation, Indexing, and Slicing of Numpy Arrays


In [2]:
import numpy as np

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
lst=[1,2,3,4,5]
arr1=np.array(lst)
arr2=np.array([5,6,7,8,9])

In [13]:
lst2=[5,6,7,8,9]

In [14]:
print(type(lst))
print(type(lst2))

<class 'list'>
<class 'list'>


In [15]:
print(lst+lst2)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [6]:
print(arr1[2])

3


In [7]:
print(arr1[-1])

5


In [9]:
print(arr1+arr2)

[ 6  8 10 12 14]


In [10]:
print(arr1[:])

[1 2 3 4 5]


In [12]:
print(arr1[::-1])

[5 4 3 2 1]
