In [1]:
harsh = [1,2,3,4]

In [2]:
print(type(harsh))

<class 'list'>


In [3]:
import numpy as np

In [4]:
harsh = np.arange(1,11)

In [5]:
print(type(harsh))

<class 'numpy.ndarray'>


In [10]:
print(harsh)


[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
harsh1 = np.array([1,2,3])

In [9]:
print(harsh1)

[1 2 3]


In [11]:
print(harsh[2])

3


In [13]:
print(harsh[2:10])

[ 3  4  5  6  7  8  9 10]


In [14]:
harsh2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

In [19]:
harsh3 = np.reshape(harsh2,shape=(4,4)) 

In [20]:
print(harsh2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [21]:
print(harsh3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [22]:
harsh4 = np.reshape(harsh3,shape=-1)

In [23]:
harsh4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1],[2]])

In [25]:
arr2

array([[1],
       [2]])

In [26]:
arr1

array([1, 2, 3])

In [27]:
print(arr1+arr2)

[[2 3 4]
 [3 4 5]]


In [28]:
arr4 = np.array([[5,6,7],[8,9,10],[15,14,13]])

In [29]:
arr4

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [15, 14, 13]])

In [34]:
arr5 = np.array([[2],[4],[6]])

In [35]:
arr5

array([[2],
       [4],
       [6]])

In [36]:
print(arr4+arr5)

[[ 7  8  9]
 [12 13 14]
 [21 20 19]]


In [37]:
harsh4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [38]:
print(harsh4[harsh4>10])

[11 12 13 14 15 16]


In [39]:
harsh4.argmax()

np.int64(15)

In [40]:
harsh4[15]

np.int64(16)

In [42]:
print(np.where(harsh4>10))

(array([10, 11, 12, 13, 14, 15]),)


In [43]:
np.where(harsh4>10)

(array([10, 11, 12, 13, 14, 15]),)

In [44]:
milan = np.array([True,False,True,False,True,True])

In [45]:
milan

array([ True, False,  True, False,  True,  True])

In [46]:
milan1 = np.array([1,2,3,4,5,6])

In [47]:
milan1

array([1, 2, 3, 4, 5, 6])

In [48]:
np.histogram(harsh4)

(array([2, 1, 2, 1, 2, 1, 2, 1, 2, 2]),
 array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. , 11.5, 13. , 14.5, 16. ]))

In [49]:
print(milan1[milan])

[1 3 5 6]


In [52]:
party_mask = np.array([True,False,True,True,False])

In [53]:
party_mask

array([ True, False,  True,  True, False])

In [54]:
room1 = np.array(['Harsh','Isha','Nihar','Kushangi','Mansi'])

In [55]:
print(room1[party_mask])

['Harsh' 'Nihar' 'Kushangi']


In [60]:
isha = np.array([1,2,3,np.nan,5,6])

In [61]:
isha

array([ 1.,  2.,  3., nan,  5.,  6.])